## ***Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes***

The Predicting of cloth reviews by women with Multi Nomial Naive Bayes

# ***Import Library***

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('https://raw.githubusercontent.com/YBI-Foundation/Teaching-Data/main/Women%20Clothing%20E-Commerce%20Review.csv')

In [5]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [7]:
df.describe()

Clothing ID           Age        Rating   Recommended  \
count  23486.000000  23486.000000  23486.000000  23486.000000   
mean     918.118709     43.198544      4.196032      0.822362   
std      203.298980     12.279544      1.110031      0.382216   
min        0.000000     18.000000      1.000000      0.000000   
25%      861.000000     34.000000      4.000000      1.000000   
50%      936.000000     41.000000      5.000000      1.000000   
75%     1078.000000     52.000000      5.000000      1.000000   
max     1205.000000     99.000000      5.000000      1.000000   

       Positive Feedback  
count       23486.000000  
mean            2.535936  
std             5.702202  
min             0.000000  
25%             0.000000  
50%             1.000000  
75%             3.000000  
max           122.000000

In [8]:
df.shape

(23486, 10)

In [27]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [28]:
df[df['Review']==""]=np.NaN

In [29]:
df['Review'].fillna("No Review",inplace=True)

In [30]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [31]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

# ***Define Target(y) and Feature(X)***

In [44]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [45]:
X=df['Review']

In [46]:
y=df['Rating']

In [47]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# ***Train Test Split***

In [48]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=2529)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# ***Get Feature Text Conversions to Tokens***

In [49]:
from sklearn.feature_extraction.text import CountVectorizer

In [50]:
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2,3),stop_words= 'english',max_features=5000)

In [51]:
X_train = cv.fit_transform(X_train)
cv.get_feature_names_out()
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [52]:
X_test=cv.fit_transform(X_test)
cv.get_feature_names_out()
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# ***Get Train Model***

In [55]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [57]:
y_pred = model.predict(X_test)
y_pred.shape
y_pred

array([2., 3., 3., ..., 5., 4., 5.])

# ***Get Probability of Each Predicted Class***

In [58]:
model.predict_proba(X_test)

array([[0.26692373, 0.35957477, 0.30830537, 0.04730174, 0.01789439],
       [0.09725869, 0.09370016, 0.48762968, 0.26285916, 0.05855232],
       [0.21322638, 0.0344866 , 0.6775651 , 0.01713515, 0.05758676],
       ...,
       [0.22922895, 0.0288237 , 0.07354507, 0.02725008, 0.6411522 ],
       [0.01591788, 0.00115913, 0.00471111, 0.76076036, 0.21745151],
       [0.06184667, 0.09982129, 0.01834076, 0.04535696, 0.77463432]])

# ***Get Model Evaluation***

In [59]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))

[[  29   26   35   32  141]
 [  48   43   91   75  186]
 [  78   96  152  172  326]
 [ 125  129  212  301  742]
 [ 327  330  394  648 2308]]


In [60]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.05      0.11      0.07       263
         2.0       0.07      0.10      0.08       443
         3.0       0.17      0.18      0.18       824
         4.0       0.25      0.20      0.22      1509
         5.0       0.62      0.58      0.60      4007

    accuracy                           0.40      7046
   macro avg       0.23      0.23      0.23      7046
weighted avg       0.43      0.40      0.42      7046



# ***Recategories Ratings as poor(0) and good(1)***

In [61]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [63]:
df.replace({'Rating':{1:0,2:0,3:0,4:1,5:1}}, inplace=True)
y=df['Rating']
X=df['Review']

# ***Train Test Split***

In [64]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size = 0.7, stratify = y, random_state=42529)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

# ***Get Feature Text Conversion to Tokens***

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(lowercase=True, analyzer='word',ngram_range=(2, 3),stop_words= 'english',max_features=5000)
X_train = cv.fit_transform(X_train)
X_test=cv.fit_transform(X_test)

# ***Get Model Re-Train***

In [66]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

# ***Get Model Prediction***

In [67]:
y_pred = model.predict(X_test)
y_pred.shape
y_pred

array([0., 0., 0., ..., 0., 0., 0.])

# **Get Model Evaluation**

In [68]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test,y_pred))

[[7046]]


In [69]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      7046

    accuracy                           1.00      7046
   macro avg       1.00      1.00      1.00      7046
weighted avg       1.00      1.00      1.00      7046

